# Generated by Django 3.1.3 on 2020-11-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpage_stream'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Página de blog', 'verbose_name_plural': 'Páginas de blog'},
        ),
    ]
