# Generated by Django 3.1.3 on 2020-11-26 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201126_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogindexpage',
            options={'verbose_name': 'Página principal do blog', 'verbose_name_plural': 'Páginas principais do blog'},
        ),
    ]
