# Generated by Django 3.1.3 on 2020-11-26 13:28

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('blog', '0005_auto_20201126_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('content', wagtail.core.fields.StreamField([('titulo_e_texto', wagtail.core.blocks.StructBlock([('titulo', wagtail.core.blocks.CharBlock(required=True)), ('texto', wagtail.core.blocks.TextBlock(help_text='Texto sem formatação', required=True))]))], blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Flex Page',
                'verbose_name_plural': 'Flex Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
