# Generated by Django 3.1.3 on 2020-11-26 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_flexpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flexpage',
            options={'verbose_name': 'Página Flex', 'verbose_name_plural': 'Páginas Flex'},
        ),
    ]
