# Generated by Django 3.1.3 on 2020-11-26 16:21

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201126_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('titulo_e_texto', wagtail.core.blocks.StructBlock([('titulo', wagtail.core.blocks.CharBlock(required=True)), ('texto', wagtail.core.blocks.TextBlock(help_text='Texto sem formatação', required=True))])), ('full_richtext', streams.blocks.RichtextBlock()), ('simple_richtext', streams.blocks.SimpleRichtextBlock())], blank=True, null=True),
        ),
    ]
