# Generated by Django 3.1.3 on 2020-11-30 12:30

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201130_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalpage',
            name='texto',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
