# Generated by Django 3.1.3 on 2020-11-30 12:58

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_linkspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalpage',
            name='texto',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
