# Generated by Django 3.1.3 on 2020-12-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='E-mail', max_length=100)),
                ('full_name', models.CharField(help_text='Nome completo', max_length=200)),
            ],
        ),
    ]
